version: "3.9"
services:
  vault:
    image: vault
    ports:
      - 9200:8200
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: myroot
      VAULT_TOKEN: myroot
      VAULT_ADDR: http://0.0.0.0:8200
  mongo:
    image: mongo
    ports:
      - 37017:27017
