# Get 'microservice' configs using 'dev' profile
GET http://localhost:8888/microservice/dev
Accept: application/json
X-Config-Token: myroot

###

GET http://localhost:8888/microservice-dev.yml
Accept: application/json
X-Config-Token: myroot

###

# Refresh Config Server
POST http://localhost:8888/actuator/refresh
Accept: application/json

###

# Refresh microservice
POST http://localhost:8080/actuator/refresh
Accept: application/json

###

# Get value of 'property' retrieved from Config Server
GET http://localhost:8080/actuator/env/myproperty
Accept: application/json

###
