management:
  endpoints:
    web:
      exposure:
        include: refresh,info

myproperty:
  application-dev.yml

server:
  error:
    include-message: always

spring:
  data:
    mongodb:
      database: ${spring.application.name}
      host: localhost
      port: 37017
